FROM php:7-apache

RUN apt-get update && \
	apt-get install -y mysql-client && \
	docker-php-ext-install pdo pdo_mysql && \
	rm -rf /var/lib/apt/lists/*

RUN mv /etc/localtime /etc/localtime.old
RUN cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

RUN echo "date.timezone = Europe/Paris" > /usr/local/etc/php/php.ini

RUN a2enmod rewrite

RUN chown -R www-data:www-data /var/www/

ADD 001-sf4-technical-test.conf /etc/apache2/sites-enabled/001-sf4-technical-test.conf

WORKDIR /var/www/symfony